//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banyan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public System.Guid id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string fullname { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public Nullable<byte> gender { get; set; }
        public string address { get; set; }
        public string identitycard { get; set; }
        public string role { get; set; }
    }
}
