//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banyan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public category()
        {
            this.food = new HashSet<food>();
        }
    
        public System.Guid id { get; set; }
        public Nullable<System.Guid> restaurantid { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<int> position { get; set; }
    
        public virtual restaurant restaurant { get; set; }
        public virtual ICollection<food> food { get; set; }
    }
}
