//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banyan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class district
    {
        public district()
        {
            this.ward = new HashSet<ward>();
        }
    
        public System.Guid id { get; set; }
        public Nullable<System.Guid> cityid { get; set; }
        public string name { get; set; }
    
        public virtual city city { get; set; }
        public virtual ICollection<ward> ward { get; set; }
    }
}
