//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banyan.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class banyandbEntities : DbContext
    {
        public banyandbEntities()
            : base("name=banyandbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<billing> billing { get; set; }
        public DbSet<billingdetail> billingdetail { get; set; }
        public DbSet<category> category { get; set; }
        public DbSet<city> city { get; set; }
        public DbSet<customer> customer { get; set; }
        public DbSet<district> district { get; set; }
        public DbSet<food> food { get; set; }
        public DbSet<restaurant> restaurant { get; set; }
        public DbSet<specialdate> specialdate { get; set; }
        public DbSet<ward> ward { get; set; }
        public DbSet<admin> admin { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
